# Generated by Django 2.2 on 2022-04-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'Promotions'},
        ),
    ]
