# Generated by Django 2.2 on 2022-04-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220423_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
