# Generated by Django 2.2 on 2022-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('contacts', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
