# Generated by Django 2.2 on 2022-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contacts',
            field=models.TextField(),
        ),
    ]
