# Generated by Django 2.2 on 2022-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220502_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
