# Generated by Django 2.2 on 2022-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220502_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
